Fix hugo binary download URL
alestic/aws-lambda-codepipeline-site-generator-hugo pull request #7
Opened 2017-10-07 05:48 UTC by yexingok

The Hugo download URL and hugo binary have been changed.

Tested on Amazon Linux works as expected.

2018-02-15 21:51 UTC, ehammond requested changes
Thank you for this submission. It would be good to support the latest versions of hugo. Unfortunately, this commit breaks support for versions 0.14, 0.15, 0.16, as the URL formats were different then. In addition, 0.14 through 0.17 extracted into a subdirectory so the "mv" still needs to be performed for them. Please adjust so that those specific old versions still download correctly. We want to continue supporting these specific old versions as people are running sites using them.

2018-02-23 14:33 UTC, yexingok commented
Hi @ehammond ,

I just made a new commit to support hugo version >= 0.11 

Tested on Amazon Linux and Centos7 works well, 

Please review, thanks.

2018-02-27 04:21 UTC, merged

2018-02-27 04:25 UTC, ehammond commented
Thanks for putting this together!

I have updated all of the previously uploaded hugo versions, and added s3://run.alestic.com/lambda/aws-lambda-site-generator-hugo-0.36.1.zip

2018-02-27 06:08 UTC, yexingok commented
Thank you, cheers!